Initial implementation

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -17,14 +17,15 @@ jobs:
 
     services:
       mariadb:
-        image: mariadb:10.5
+        image: mariadb:lts
         env:
           MYSQL_DATABASE: photoview_test
           MYSQL_USER: photoview
           MYSQL_PASSWORD: photosecret
           MYSQL_RANDOM_ROOT_PASSWORD: yes
+        # https://github.com/MariaDB/mariadb-docker/issues/497
         options: >-
-          --health-cmd="mysqladmin ping"
+          --health-cmd="mariadb-admin ping"
           --health-interval=10s
           --health-timeout=5s
           --health-retries=5
@@ -32,7 +33,7 @@ jobs:
           - 3306:3306
 
       postgres:
-        image: postgres:13.2
+        image: postgres:16-alpine
         env:
           POSTGRES_USER: photoview
           POSTGRES_PASSWORD: photosecret
@@ -64,6 +65,7 @@ jobs:
         cache-to: type=gha,mode=max
 
     - name: Test
+      id: test
       run: |
         docker run --name test --network host \
             -e PHOTOVIEW_DATABASE_DRIVER=${{ matrix.database }} \
@@ -76,6 +78,7 @@ jobs:
 
     - name: Upload coverage
       uses: codecov/codecov-action@v4
+      if: ${{ steps.test.conclusion == 'success' || steps.test.conclusion == 'failure' }}
       with:
         flags: api-${{ matrix.database }}
 
@@ -102,11 +105,32 @@ jobs:
         cache-to: type=gha,mode=max
 
     - name: Test
+      id: test
       run: |
         docker run --name test photoview/ui npm run test:ci
         docker cp test:/app/ui/coverage ./ui/
 
     - name: Upload coverage
       uses: codecov/codecov-action@v4
+      if: ${{ steps.test.conclusion == 'success' || steps.test.conclusion == 'failure' }}
       with:
         flags: ui
+
+    - name: Run ESLint
+      working-directory: ui
+      run: |
+        npm run lint:ci || true
+        echo "--------------------------"
+        echo "ESLint execution results :"
+        echo "--------------------------"
+        cat ./eslint-report.txt || echo "ESLint report file not found."
+
+    - name: ESLint artifact
+      id: eslint-artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: ESLint-report
+        path: ./ui/eslint-report.txt
+        if-no-files-found: warn
+        compression-level: 9
+        overwrite: true
